#!/bin/bash
git pull && git submodule init && git submodule update && git submodule status

rm ~/.vimrc
rm -rf ~/.vim
rm ~/.editorconfig

cp vimrc ~/.vimrc
cp -r .vim ~/

cp .editorconfig ~/.editorconfig

rm ~/.psqlrc
cp psqlrc ~/.psqlrc

rm ~/.ackrc
cp ackrc ~/.ackrc

os=`uname -a`

if [[ $os == *"Darwin"* ]]; then
    rm ~/.bash_profile
    cp bashrc ~/.bash_profile
    source ~/.bash_profile
    echo "NOW RUN source ~/.bash_profile"
else
    rm ~/.bashrc
    cp bashrc ~/.bashrc
    source ~/.bashrc
    echo "NOW RUN source ~/.bashrc"
fi 
