#!/bin/bash
git pull && git submodule update --init --recursive && git submodule status

rm -rf ~/.vim
cp -r .vim ~/

cp tmux.conf ~/.tmux.conf

cp vimrc ~/.vimrc

cp .editorconfig ~/.editorconfig

cp psqlrc ~/.psqlrc

cp ackrc ~/.ackrc

cp gitconfig ~/.gitconfig

os=`uname -a`

if [[ $os == *"Darwin"* ]]; then
    rm ~/.bash_profile
    cp bashrc ~/.bash_profile
    source ~/.bash_profile
    echo "NOW RUN source ~/.bash_profile"
else
    rm ~/.bashrc
    cp bashrc ~/.bashrc
    source ~/.bashrc
    echo "NOW RUN source ~/.bashrc"
    if [ -d "/opt/spensa/agportal" ]; then
        echo 'cd /opt/spensa/agportal' >> ~/.bashrc
    fi
fi 

sudo pip install -r requirements.txt
